### PR TITLE
Specified SNIP-25 - Improvements to allowance

### PR DESCRIPTION
**Pull request by reuvenpo**
This PR describes SNIP-24 which specifies:

* `IncreaseAllowanceEx` and `DecreaseAllowanceEx` messages allowing richer control of allowance expiration
* `AllowanceEx` query which is able to fully show the expiration parameters
* A new `available` field in `Allowance` and `AllowanceEx` which lets accounts see how much of the given allowance is available to them.

UPDATE 2021-05-27: We decided to shelve this SNIP for now. We explained the rationale in a [comment below](https://github.com/SecretFoundation/SNIPs/pull/13#issuecomment-849544727).

### CODE REVIEW

**Comment by hieu-lai** [comment]
Sorry to bring this up again, in case it was overlooked, is querying the list of approved allowances a no go?

**Comment by reuvenpo** [comment]
Hey there @hieu-lai , your question is completely valid, i suppose we should have written down our rationale.
We investigated several alternatives to implementing the `AllAllowances` query, but at the end of the day we couldn't find a solution that didn't have a significant and unbounded cost impact on the contracts. The issue is that to store the set of allowances without duplicates you'd need to store them all in one location in storage. As you give more allowances to more accounts, that storage access will have to read and write bigger and bigger blobs of data.
Since users will want to access this information quite rarely anyways, we think the better approach is to have clients (wallets, applications, etc) that want to show this info, just query whether or not the user granted allowance to the contracts the client cares about, using the existing [`Allowance` query](https://github.com/SecretFoundation/SNIPs/blob/master/SNIP-20.md#Allowance)

**Comment by hieu-lai** [comment]
Ahh cool cool cool. Thanks for the explanation.

**Comment by reuvenpo** [comment]
Hello Community!

After discussing this SNIP again internally, we unfortunately decided to shelve it for now. There are several reasons for this:
* This proposal adds significant additional API for a relatively small improvement to usability. The `Never` expiration mode can be emulated by setting a timestamp expiration to `u64::MAX` (as we already do in SecretSwap), and we do not have a compelling use case for specifying expiration based on block height that can not be similarly emulated by timestamp based expiration (yes, it will be less accurate, but we didn't find a need for that accuracy in block heights).
* The `available` field of allowance has two unwanted implications:
    * In order to know the block height of the chain during the query (to some accuracy) we need to store the block height in every handle. This adds a global gas tax to all messages of around 4-5K gas (not terrible but adds up
    * If the viewing key for some token (TOK) of some contract (APP) is publicly known for some reason, then any user that gives APP an infinite allowance in TOK will effectively allow everyone to know their TOK balance. This is unfortunately the case with SecretSwap pairs [[1](https://github.com/enigmampc/SecretSwap/blob/master/contracts/secretswap_pair/src/contract.rs#L38)].
* A solution for the above bullet point is to add another optional field called `expose_available` to `{In,De}creaseAllowanceEx` which would say whether or not querying the particular allowance would also show the available balance of the granter. This field would be `false` by default and not available in the original `{In,De}creaseAllowance`. The issue is that doing that adds even more API surface for a feature without a concrete use case (that can't be easily achieved with the existing interfaces.

The [current PR to the reference implementation](https://github.com/enigmampc/snip20-reference-impl/pull/16) contains a bug fix unrelated to this SNIP. That bug fix will be implemented as its own PR while the current PR to the refrence will be be closed for now.

We welcome community discussion into specific products that would benefit from these features being added, as well as drafting a better version of this specification that could answer those needs in the best possible way.

Thank you for understanding, and thanks for everyone that took the time to review and comment on this PR (here and on discord), and especially to @baedrik which helped create the current design.

**Comment by baedrik** [comment]
I wasn't aware that secret swap pairs have publicly known viewing keys.  I agree the side effect of making every secret swap users' balances public is enough reason to not implement the `available` field unless `expose_available` is also implemented. 

@reuvenpo Since it won't be implemented, the following is just purely academic...

For Snip20s, saving the BlockInfo for queries shouldn't be necessary.  Since the main use for `available` is for a contract to know in advance whether a Transfer(/send/burn)From will fail, the contract can provide the time of its execution BlockInfo as a field in the QueryMsg.  If it chooses to lie for some reason, it only hurts itself by receiving an inaccurate QueryResponse that might break its own processing.  And if a person uses the query, changing the time to see what their allowance was/will be at different points in time doesn't really have any impact, because it doesn't affect the actual attempt to transfer.

The only reason Snip721s have to save the BlockInfo is because it can't trust the querier for things like querying private metadata because someone would be able to benefit from backdating a query to before expiration to see the current private metadata.  So Snip721s can't let users provide the time, but Snip20s would be ok taking the time as input because allowances are only for transfers (not information)

**Comment by reuvenpo** [comment]
>I wasn't aware that secret swap pairs have publicly known viewing keys

Yeah it's a detail i learned about pretty recently. I was trying to think of what issues could arise from always returning the `available` field and it hit me that it could leak important information if you break the assumption that the contract's viewing key is private. Then I remembered that we actually already do it, which turned the threat from theoretical to very real.

>For Snip20s, saving the BlockInfo for queries shouldn't be necessary. ...

Interesting approach! I didn't consider it but it's worth keeping in mind for future designs.

>The only reason Snip721s have to save the BlockInfo is because...

Keep in mind that the block time isn't strictly trusted, so an attacker could still get around that. but for general purpose use it's good enough.

>Snip20s could probably get away as long as users are aware that granting permission to view their balance ... is a permission that can only be revoked by decreasing the allowance to 0

That or doing something like `IncreaseAllowance(..., expose_available=false)` to set that field back to false. But yeah i catch your drift, it's sensible that you might need to actively revoke a permission. I believe that in practice it'll rarely be an issue - contracts designed to work with allowance will probably know to watch out for that (if we'll caution against these things in the SNIP itself)

**Comment by baedrik** [comment]
> Yeah it's a detail i learned about pretty recently
Is there any concern that someone with the time/resources to match up transfer histories could piece together anyone's swap/provide history?  I know that the AMM wasn't advertised as private, but just wondering what your thoughts were.

> Keep in mind that the block time isn't strictly trusted, so an attacker could still get around that. but for general purpose use it's good enough.
Yeah those were my thoughts too.  For most uses that will be fine, but any app that needs to strictly enforce viewing (query) expirations would want to have some time oracle to serve their snip721 contract

**Comment by reuvenpo** [comment]
>Can this VK be used to reconstruct people's swapping history?

Yes, this makes it a lot easier to do than trying to analyze the pools just based on observing their size over time. I don't like this but like you said the AMM was never advertised as completely private. We should definitely be clear about this in our communication, and idk this might turn into a "feature" letting us build a "swap explorer" of sorts

>stricter kwonledge of block times

I think a time oracle would be helpful for things like Dead Man Switches, where some information may only be revealed after some time, but i think that doing the opposite (hiding information after some time) is technically impossible because you can always rewind the blockchain.

**Comment by baedrik** [comment]
> but i think that doing the opposite (hiding information after some time) is technically impossible because you can always rewind the blockchain

True, you wouldn't ever be able to rewind the clock and prevent them from viewing again information that you once allowed them to view, but I guess I'm still not clear as to the extent that "block time isn't strictly trusted".  I.e., if you can replay txs on a fork, but give them altered timestamps, you would be able to view an update that happened to the metadata *after* your expiration expired by making the network believe that the update happened earlier.  But a time oracle could prevent that (if it is even possible to begin with)

**Comment by reuvenpo** [comment]
A time oracle mostly pushes the problem to another location. The way storage works is that when reading you'll at worst get an outdated value. Let's say only a privileged address is allowed to update the oracle state, so you know its storage will only ever have non-future block heights. When another contract is querying the oracle, an attacker could intercept the storage access and return an old value for "most recent known block". This could be far back enough that the expiration is still valid. Of course this can't override consensus, but in a local fork that's good enough.

**Comment by baedrik** [comment]
Ah ok.  Yeah, I see what you are saying.  Also, since you can see transactions that go to the time oracle contract, on a fork, you could also just filter those tx out to stop time, or filter some out to slow it

**Comment by assafmo** [comment]
Please rename to SNIP24 :relaxed:

**Comment by reuvenpo** [comment]
I'll keep the branch name as SNIP-23 because i don't know how to change the branch this PR uses.

**Comment by ertemann** [comment]
@assafmo can we close this?

**Comment by blake-regalia** [comment]
I suggest closing this issue as I believe the points have been addressed with the introduction of [SNIP-26](https://github.com/SecretFoundation/SNIPs/blob/master/SNIP-26.md).

**Comment by assafmo** [comment]
Thanks guys.

**Pull request closed without merging**
