### PR TITLE
Rewritten the SNIP-20 spec

### PR DESCRIPTION
**Pull request by reuvenpo**
This PR is a rewrite of the SNIP-20 specification based on the lessons learned when writing [the reference implementation](https://github.com/enigmampc/snip20-reference-impl) and [secretSCRT](https://github.com/enigmampc/secretSCRT).

### CODE REVIEW

**Comment by baedrik** [comment]
Looks great!  
I do have a question about the Allowance query.  It states:
"Both the spender and owner are allowed to make this query, for every pair of accounts. i.e. every account can know how much allowance it has given, and how much it has been given."

That implies that others can't make this query, but since the querier can't be identified, in reality anyone can make the query if they have the key.  Perhaps it is clearer to just state that:

"The viewing key should be provided to any account that would require knowledge of its allowance limits."

This does bring up another question of whether there should be different keys for viewing allowances and viewing balances/transactions.  Currently with one viewing key, any person/contract you give the key to because you want them to see how much their allowance is can also check your transaction history and balance.  Should that information be available to any account you just want to be able to check their allowance?  My leaning would be towards a separate key for viewing allowances, but that's just my $0.02

Also, I noticed that the snip20-reference-impl has an "expiration" key in QueryAnswer::Allowance that isn't mentioned in the SNIP-20 spec.  Should "expiration" also be added to the HandleAnswer::IncreaseAllowance and HandleAnswer::DecreaseAllowance enums (and reflected in the spec)?

**Comment by baedrik** [comment]
Just sharing a couple other thoughts...
If we think a separate key to view allowances is a good idea, we also have to determine whether each allowance viewing key should only work for one specific spender address.  I can see an argument being made that if someone was using two competing dApps, letting one contract use the allowance viewing key also lets it spy on how much allowance you are giving its competitor.

Granted, mapping each spender address to a unique key to view only its allowance might be overkill.  We could just suggest in the spec that any time it is critical to keep allowance limits private, tokens should be transferred to the contract instead of using allowances.  But that being said, I still like the idea of not being able to use an allowance viewing key to view balances or transaction history.

**Comment by reuvenpo** [comment]
@baedrik 
On the topic of phrasing in Allowance, I agree that it can be made clearer, I'll try to word it to make clear that the viewing keys of either one of the accounts is required, rather than the accounts themselves.

On the topic of multiple viewing keys, people are not expected to send their VK to other individuals, but rather to other contracts. Since the contract code can be verified and audited (if it was built in a reproducible way), and can not be changed, you have the ability of making sure that you send it to contracts that don't access information that they aren't supposed to, without your consent. I think this also answers your concerns in your second comment.

On the topic of expiration in allowance - you are correct, this was an oversight. it will be added.

**Comment by baedrik** [comment]
Ah, after reading the update, I understand.  You don't even have to provide a viewing key since the spender can just use their own.  Yeah, all my concerns were based on misunderstanding lol.  Thanks for clearing that up!

**Pull request merged**
